### ISSUE TITLE
iOS, with the new fix the picker only works in darkmode

### ISSUE THREAD

**Issue by BaltaKid** [PingAK9/MobileDialog-Unity#10]
Hello,
I have been testing the plugin and I found that with the fix to work with dark mode this happens in light mode.

![Photo 22-07-2020, 12 01 47](https://user-images.githubusercontent.com/30121684/88169202-94bbc500-cc13-11ea-8e22-c23b4972fe9d.png)

**Comment by khanhuitse05** [comment]
https://github.com/PingAK9/Mobile-Dialog-Unity/blob/master/native-dialog/Assets/Plugins/iOS/PopupNative/IOSNativeDatePicker.mm

Can you try fix on this file (about at line 80)? Edit directly on your Xcode. (You do not need rebuild unity).

**Comment by BaltaKid** [comment]
Hello PinkAK9,
What should i replace to work in light and dark mode?
`   UIView *darkView = [[UIView alloc] initWithFrame:CGRectMake(0, vc.view.bounds.size.height, [self GetW], 260)];
    darkView.alpha = 1;
    darkView.backgroundColor = [UIColor blackColor];
    darkView.tag = 9;
    
    UIView *whiteView = [[UIView alloc] initWithFrame:vc.view.bounds];
    whiteView.alpha = 1;
    whiteView.backgroundColor = [[UIColor alloc] initWithRed:1 green:1 blue:1 alpha:0];
    whiteView.tag = 8;`

**Comment by akozlev** [comment]
Did you have any success in fixing it ?

**Comment by BaltaKid** [comment]
> Did you have any success in fixing it ?

Nop

**Comment by BaltaKid** [comment]
> https://github.com/PingAK9/Mobile-Dialog-Unity/blob/master/native-dialog/Assets/Plugins/iOS/PopupNative/IOSNativeDatePicker.mm
> 
> Can you try fix on this file (about at line 80)? Edit directly on your Xcode. (You do not need rebuild unity).

Can you explain better how to do that?

**Comment by nimrodbens** [comment]
adding this solved it for me

    darkView.backgroundColor = [UIColor whiteColor];
    if (@available(iOS 12.0, *)) {
        if (darkView.traitCollection.userInterfaceStyle == UIUserInterfaceStyleDark) {
            darkView.backgroundColor = [UIColor blackColor];
        } else {
            darkView.backgroundColor = [UIColor whiteColor];
        }
    }

**Comment by BaltaKid** [comment]
@nimrodbens  I don't know what i did wrong but mine is like this
![Photo 06-10-2020, 11 13 02](https://user-images.githubusercontent.com/30121684/95190217-dd246100-07c6-11eb-962f-2c7c707eeb18.png)

**Comment by nimrodbens** [comment]
sorry i only tested it on the date picker. not time picker. 

but eventually i ended up not using this tool, because it broke my android project. it didn't even build in unity when the platform was android. did you guys not experience this?

**Comment by BaltaKid** [comment]
@nimrodbens No on android is working fine, what tool are you using to solve this problem?

**Comment by nimrodbens** [comment]
didn't find anything else that works. are you using the latest unity version and all? maybe i'm missing something?

i added the `NativePopupPlugin.jar` file to the `Plugins/Android` folder and also copied the `MobileNative` folder to my Assets folder.

**Comment by BaltaKid** [comment]
I'm using Unity 2020.1.3 can you send me the error?

**Comment by nimrodbens** [comment]
i just tested the time picker and it works great for me both on light/dark mode.

in file `IOSNativeDatePicker.mm` in Xcode, under this line (i think it's line 76):

    darkView.alpha = 1;

add this code:

    if (@available(iOS 12.0, *)) {
        if (darkView.traitCollection.userInterfaceStyle == UIUserInterfaceStyleDark) {
            darkView.backgroundColor = [UIColor blackColor];
        } else {
            darkView.backgroundColor = [UIColor whiteColor];
        }
    } else {
        darkView.backgroundColor = [UIColor whiteColor];
    }

**Comment by nimrodbens** [comment]
sorry you can just change the code in `Plugins/iOS/PopupNative/IOSNativeDatePicker.mm` and then build again in unity.

if that doesn't work you can change it in Xcode.

**Comment by nimrodbens** [comment]
also somehow android now builds for me. if that error will reoccur i will send you the error. thank you!

let me know if iOS works for you.

**Comment by nimrodbens** [comment]
i created a pull request to fix this thing. it's my first time creating a pull request so i hope i got things right in terms of how to create it.

https://github.com/PingAK9/Mobile-Dialog-Unity/pull/11

**Comment by BaltaKid** [comment]
The problem occurs in iOS 14

**Comment by nimrodbens** [comment]
it happened to me as well on iOS 13 and what i wrote fixed it. i didn't check it on iOS 14 though.. if i will get a chance i will update about it. currently i don't have a setup for iOS 14.

**Comment by nimrodbens** [comment]
just tested it on iOS 14 as well and it works great both on light/dark mode.

**Comment by khanhuitse05** [comment]
Thank you @nimrodbens. I merged your PR.
