### ISSUE TITLE
Date and time pickers invisible when iOS theme set to black, how to solve

### ISSUE THREAD

**Issue by OhCarson** [PingAK9/MobileDialog-Unity#9]
Fixed by setting line 77 of IOSNativeDatePicker.mm from
darkView.backgroundColor = [UIColor whiteColor];
to  
darkView.backgroundColor = [UIColor blackColor];

probably the same for timer
not sure where to post this, but fixed it for me on SDK 13.5

**Comment by khanhuitse05** [comment]
Thanks for your report. Both Date and Time use the same widget
